# Generated by Django 5.0.3 on 2024-03-29 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_clientes_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NB', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('observacao', models.TextField()),
                ('instituidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_instituidor_requerimento', to='clientes.cliente')),
                ('requerente_titular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente_titular_requerimento', to='clientes.cliente')),
            ],
        ),
    ]
