# Generated by Django 5.0.3 on 2024-03-29 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_requerimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='requerimento',
            name='requerente_dependentes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimento',
            name='tutor_curador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_tutor_curador_requerimento', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='requerimento',
            name='NB',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
