# Generated by Django 5.0.3 on 2024-03-29 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_estado_servico_requerimento_requerente_dependentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimento',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estado_requerimento', to='clientes.estado'),
        ),
        migrations.AddField(
            model_name='requerimento',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servico_requerimento', to='clientes.servico'),
        ),
    ]
