# Generated by Django 5.0.3 on 2024-03-29 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_requerimento_estado_requerimento_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimento',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_requerimento', to='clientes.estado'),
        ),
        migrations.AlterField(
            model_name='requerimento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servico_requerimento', to='clientes.servico'),
        ),
    ]
