# Generated by Django 5.0.3 on 2024-04-06 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_requerimento_estado_alter_requerimento_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Natureza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exigência',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protocolo', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('NB', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NB_exigencia', to='clientes.requerimento')),
                ('natureza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='natureza_exigencia', to='clientes.natureza')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protocolo', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('observacao', models.TextField()),
                ('NB', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NB_recurso', to='clientes.requerimento')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_recurso', to='clientes.estado')),
            ],
        ),
    ]
