# Generated by Django 5.0.3 on 2024-04-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_rename_exigência_exigencia_remove_recurso_natureza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimento',
            name='NB',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
