# Generated by Django 5.0.3 on 2024-04-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_rename_exigência_exigencia_remove_recurso_natureza'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='arquivo_do_cliente',
            field=models.FileField(blank=True, null=True, upload_to='arquivo_clientes/'),
        ),
        migrations.AddField(
            model_name='exigencia',
            name='arquivo_da_exigencia',
            field=models.FileField(blank=True, null=True, upload_to='arquivo_exigencias/'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='arquivo_do_recurso',
            field=models.FileField(blank=True, null=True, upload_to='arquivo_recursos/'),
        ),
        migrations.AddField(
            model_name='requerimento',
            name='arquivo_do_requerimento',
            field=models.FileField(blank=True, null=True, upload_to='arquivo_requerimentos/'),
        ),
    ]
