# Generated by Django 5.0.3 on 2024-04-23 00:41

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_alter_requerimento_arquivo_do_requerimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='arquivo_do_cliente',
            field=models.FileField(blank=True, null=True, upload_to=clientes.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='exigencia',
            name='arquivo_da_exigencia',
            field=models.FileField(blank=True, null=True, upload_to=clientes.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='arquivo_do_recurso',
            field=models.FileField(blank=True, null=True, upload_to=clientes.models.path_and_rename),
        ),
    ]
