# Generated by Django 5.0.3 on 2024-04-27 11:04

import clientes.models
import clientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_exigencia_slugfied_protocolo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='arquivo_do_cliente',
            field=models.FileField(blank=True, null=True, upload_to=clientes.models.path_and_rename, validators=[clientes.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='exigencia',
            name='arquivo_da_exigencia',
            field=models.FileField(blank=True, null=True, upload_to=clientes.models.path_and_rename, validators=[clientes.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='arquivo_do_recurso',
            field=models.FileField(blank=True, null=True, upload_to=clientes.models.path_and_rename, validators=[clientes.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='requerimento',
            name='arquivo_do_requerimento',
            field=models.FileField(blank=True, null=True, upload_to=clientes.models.path_and_rename, validators=[clientes.validators.validate_file_extension]),
        ),
    ]
