# Generated by Django 5.0.3 on 2024-05-01 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_remove_exigencia_slugfied_protocolo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exigencia',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='estado_exigencia', to='clientes.estado'),
            preserve_default=False,
        ),
    ]
