# Generated by Django 5.0.3 on 2024-05-08 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_exigencia_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exigencia',
            old_name='data',
            new_name='data_final_prazo',
        ),
        migrations.RenameField(
            model_name='recurso',
            old_name='data',
            new_name='data_final_prazo',
        ),
        migrations.RemoveField(
            model_name='exigencia',
            name='protocolo',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='protocolo',
        ),
    ]
