# Generated by Django 5.0.3 on 2024-06-01 01:10

import app.utils.storage_backend
import clientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_cliente_is_deleted_exigencia_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='arquivo_do_cliente',
            field=models.FileField(blank=True, null=True, storage=app.utils.storage_backend.PrivateMediaStorage(), upload_to='', validators=[clientes.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='exigencia',
            name='arquivo_da_exigencia',
            field=models.FileField(blank=True, null=True, storage=app.utils.storage_backend.PrivateMediaStorage(), upload_to='', validators=[clientes.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='arquivo_do_recurso',
            field=models.FileField(blank=True, null=True, storage=app.utils.storage_backend.PrivateMediaStorage(), upload_to='', validators=[clientes.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='requerimento',
            name='arquivo_do_requerimento',
            field=models.FileField(blank=True, null=True, storage=app.utils.storage_backend.PrivateMediaStorage(), upload_to='', validators=[clientes.validators.validate_file_extension]),
        ),
    ]
